<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE students SYSTEM "student.dtd">
<!--<!DOCTYPE students[-->
<!--		<!ELEMENT students (student*) > &lt;!&ndash; 根标签为students,子标签可以有多个student标签&ndash;&gt;-->
<!--		<!ELEMENT student (name,age,sex)>   &lt;!&ndash; student中的标签包含 name,age,sex这三个子标签 &ndash;&gt;-->
<!--		<!ELEMENT name (#PCDATA)>   &lt;!&ndash; name的值为字符串&ndash;&gt;-->
<!--		<!ELEMENT age (#PCDATA)>-->
<!--		<!ELEMENT sex (#PCDATA)>-->
<!--		<!ATTLIST student number ID #REQUIRED>  &lt;!&ndash;ATTLIST:属性 number：数字 #REQUIRED：必填 student后面必须接上一个id属性值为数字&ndash;&gt;-->
<!--		]>-->
<students>
	<student number="student01">
		<name>zhangsan</name>
		<age>18</age>
		<sex>male</sex>
	</student>
</students>
